"""
report_generator.py — Generate a PDF candidate report using ReportLab
"""

import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from database.database import get_violations, get_risk_score

REPORTS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "reports")
os.makedirs(REPORTS_DIR, exist_ok=True)

# Risk thresholds
def risk_label(score: int) -> str:
    if score <= 20:   return "Safe"
    elif score <= 50: return "Needs Review"
    else:             return "High Risk"

def risk_color(score: int):
    if score <= 20:   return colors.HexColor("#3B6D11")
    elif score <= 50: return colors.HexColor("#854F0B")
    else:             return colors.HexColor("#A32D2D")


def generate_report(candidate_name: str, identity_verified: bool = True) -> str:
    """
    Generate a PDF report for the candidate.
    Returns the output file path.
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{candidate_name}_report_{timestamp}.pdf"
    filepath = os.path.join(REPORTS_DIR, filename)

    violations = get_violations(candidate_name)
    score = get_risk_score(candidate_name)

    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "Title", parent=styles["Heading1"],
        fontSize=18, textColor=colors.HexColor("#26215C"),
        spaceAfter=6
    )
    subtitle_style = ParagraphStyle(
        "Subtitle", parent=styles["Normal"],
        fontSize=10, textColor=colors.HexColor("#5F5E5A"),
        spaceAfter=4
    )
    section_style = ParagraphStyle(
        "Section", parent=styles["Heading2"],
        fontSize=12, textColor=colors.HexColor("#3C3489"),
        spaceBefore=12, spaceAfter=6
    )
    normal = styles["Normal"]

    story = []

    # ── Header ──────────────────────────────────────────────
    story.append(Paragraph("AI Recruiter — Candidate Report", title_style))
    story.append(Paragraph(
        f"Generated: {datetime.now().strftime('%d %B %Y, %H:%M')}  |  "
        f"System: AI-Powered Proctoring v1.0",
        subtitle_style
    ))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#B4B2A9")))
    story.append(Spacer(1, 0.3*cm))

    # ── Candidate summary ────────────────────────────────────
    story.append(Paragraph("Candidate Summary", section_style))

    id_text  = "✓ Verified" if identity_verified else "✗ Not verified"
    id_color = "#3B6D11" if identity_verified else "#A32D2D"
    rl_label = risk_label(score)
    rl_color = risk_color(score)

    summary_data = [
        ["Candidate name", candidate_name],
        ["Interview date", datetime.now().strftime("%d %B %Y")],
        ["Identity", id_text],
        ["Risk score", f"{score} — {rl_label}"],
    ]
    summary_table = Table(summary_data, colWidths=[5*cm, 12*cm])
    summary_table.setStyle(TableStyle([
        ("FONTNAME",    (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE",    (0, 0), (-1, -1), 10),
        ("FONTNAME",    (0, 0), (0, -1), "Helvetica-Bold"),
        ("TEXTCOLOR",   (0, 0), (-1, -1), colors.HexColor("#2C2C2A")),
        ("TEXTCOLOR",   (1, 2), (1, 2), colors.HexColor(id_color)),
        ("TEXTCOLOR",   (1, 3), (1, 3), rl_color),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("LINEBELOW",   (0, 0), (-1, -2), 0.3, colors.HexColor("#D3D1C7")),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 0.5*cm))

    # ── Disclaimer ──────────────────────────────────────────
    story.append(Paragraph(
        "<i>This report is generated by an AI observation system and is intended to assist "
        "human review only. All final decisions regarding candidate integrity must be made "
        "by the recruiter or invigilator.</i>",
        ParagraphStyle("Disclaimer", parent=normal, fontSize=9,
                       textColor=colors.HexColor("#888780"),
                       backColor=colors.HexColor("#F1EFE8"),
                       borderPadding=(6, 8, 6, 8))
    ))
    story.append(Spacer(1, 0.4*cm))

    # ── Violation counts ─────────────────────────────────────
    story.append(Paragraph("Violation Summary", section_style))

    event_types = [
        "Looking Away", "Talking", "No Face",
        "Phone Detected", "Multiple Faces", "Identity Mismatch", "Mouth Open"
    ]
    counts = {e: 0 for e in event_types}
    points = {e: 0 for e in event_types}
    for v in violations:
        ev = v["event"]
        if ev in counts:
            counts[ev] += 1
            points[ev] += v.get("risk_points", 0)

    header = ["Event", "Occurrences", "Risk points"]
    rows = [header]
    for ev in event_types:
        rows.append([ev, str(counts[ev]), str(points[ev])])
    rows.append(["TOTAL", "", str(score)])

    viol_table = Table(rows, colWidths=[9*cm, 4*cm, 4*cm])
    viol_style = TableStyle([
        ("FONTNAME",      (0, 0), (-1, 0),  "Helvetica-Bold"),
        ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",      (0, 0), (-1, -1), 10),
        ("BACKGROUND",    (0, 0), (-1, 0),  colors.HexColor("#EEEDFE")),
        ("TEXTCOLOR",     (0, 0), (-1, 0),  colors.HexColor("#26215C")),
        ("ALIGN",         (1, 0), (-1, -1), "CENTER"),
        ("LINEBELOW",     (0, 0), (-1, -2), 0.3, colors.HexColor("#D3D1C7")),
        ("LINEABOVE",     (0, -1), (-1, -1), 1, colors.HexColor("#534AB7")),
        ("FONTNAME",      (0, -1), (-1, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
    ])
    # Highlight rows with violations
    for i, ev in enumerate(event_types, start=1):
        if counts[ev] > 0:
            viol_style.add("BACKGROUND", (0, i), (-1, i), colors.HexColor("#FAEEDA"))
            viol_style.add("TEXTCOLOR",  (0, i), (-1, i), colors.HexColor("#854F0B"))
    viol_table.setStyle(viol_style)
    story.append(viol_table)
    story.append(Spacer(1, 0.5*cm))

    # ── Timeline ─────────────────────────────────────────────
    if violations:
        story.append(Paragraph("Event Timeline", section_style))
        tl_header = ["Time", "Event", "Points", "Screenshot"]
        tl_rows = [tl_header]
        for v in violations:
            img = os.path.basename(v["image_path"]) if v["image_path"] else "—"
            tl_rows.append([
                v["timestamp"],
                v["event"],
                str(v.get("risk_points", 0)),
                img
            ])
        tl_table = Table(tl_rows, colWidths=[2.5*cm, 5*cm, 2.5*cm, 7*cm])
        tl_table.setStyle(TableStyle([
            ("FONTNAME",      (0, 0), (-1, 0),  "Helvetica-Bold"),
            ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE",      (0, 0), (-1, -1), 9),
            ("BACKGROUND",    (0, 0), (-1, 0),  colors.HexColor("#EEEDFE")),
            ("TEXTCOLOR",     (0, 0), (-1, 0),  colors.HexColor("#26215C")),
            ("LINEBELOW",     (0, 0), (-1, -2), 0.2, colors.HexColor("#D3D1C7")),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING",    (0, 0), (-1, -1), 4),
            ("TEXTCOLOR",     (0, 1), (-1, -1), colors.HexColor("#3d3d3a")),
        ]))
        story.append(tl_table)

    # ── Footer ───────────────────────────────────────────────
    story.append(Spacer(1, 1*cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#B4B2A9")))
    story.append(Paragraph(
        "AI-Powered Smart Recruitment and Online Proctoring System — for recruiter use only",
        ParagraphStyle("Footer", parent=normal, fontSize=8,
                       textColor=colors.HexColor("#B4B2A9"), spaceBefore=4)
    ))

    doc.build(story)
    print(f"[Report] Saved: {filepath}")
    return filepath
